name: Maven Web Testing with Allure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar JDK 21
      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Paso 3: Configurar Maven
      - name: Setup Maven
        uses: s4u/setup-maven@v2
        with:
          maven-version: '3.9.5'

      # Paso 4: Instalar dependencias Maven
      - name: Install Maven dependencies
        run: mvn install

      # Paso 5: Ejecutar pruebas Maven
      - name: Run tests
        run: mvn test

      # Paso 6: Configurar Allure para la generación de reportes
      - name: Install Allure CLI
        run: |
          curl -o allure.tgz -sL https://github.com/allure-framework/allure2/releases/latest/download/allure-2.21.0.tgz
          tar -xzf allure.tgz
          sudo mv allure-2.21.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      # Paso 7: Generar y guardar reportes Allure
      - name: Generate Allure Report
        run: |
          allure generate target/allure-results --clean -o allure-report
        continue-on-error: true

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
