name: CI/CD Challenge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      browserName:
        description: 'Browser type'
        required: false
        type: string
        default: 'chrome'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      ALLURE_RESULTS_PATH: allure-results

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Build project
        id: build
        run: mvn clean compile

      - name: Run tests with browser parameter
        if: steps.build.outcome == 'success'
        run: |
          mvn test -DbrowserName=${{ github.event.inputs.browserName || 'chrome' }}

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Generate Allure Report
        if: steps.build.outcome == 'success'
        run: |
          mkdir -p allure-report
          allure generate ${{ env.ALLURE_RESULTS_PATH }} -o allure-report --clean

      - name: Upload Allure Results
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

      - name: Deploy Allure Report to GitHub Pages
        if: steps.build.outcome == 'success'
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: allure-report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
